web_app/config/routes.rb
Rails.application.routes.draw do
  root to: "predictions#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :predictions do
    member do
      get :upvote
      get :downvote
    end
  end
end

web_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

web_app/app/models/prediction.rb
class Prediction < ApplicationRecord
  mount_uploader :image, ImageUploader

  enum status: {
    in_progress: 0,
    error: 1,
    completed: 2,
  }
  def vote(param)
    if param == 'upvote'
      Prediction.update_counters(self.id, upvote: 1)
    end
    if param == 'downvote'
      Prediction.update_counters(self.id, downvote: 1)
    end
  end
end

web_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

web_app/app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController

  def index
    @predictions = Prediction.all.order(id: :desc)
  end

  def show
    @prediction = Prediction.find(params[:id])
  end

  def new
    @prediction = Prediction.new

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @prediction = Prediction.new
    @prediction.image = prediction_params[:image]
    @prediction.status = :in_progress
    @prediction.save

    # result = ::Extract.new.get_prediction(@prediction)
    PredictionJob.perform_later(@prediction)
    redirect_to prediction_path(@prediction)
  end

  def destroy
    @prediction = Prediction.find(params[:id])

    @prediction.destroy

    redirect_to predictions_path
  end

  def upvote
    prediction = Prediction.find(params[:id])

    if cookies[prediction.id].nil?
      prediction.vote('upvote')
      prediction.save!
      cookies[prediction.id] = {
        value: true
      }
    else
    flash[:error] = 'Already voted'
    end
    redirect_to prediction_path(prediction)
  end

    def downvote
    prediction = Prediction.find(params[:id])

    if cookies[prediction.id].nil?
      prediction.vote('downvote')
      prediction.save!
      cookies[prediction.id] = {
        value: true
      }
    else
    flash[:error] = 'Already voted'
    end
    redirect_to prediction_path(prediction)
  end

  private

  def prediction_params
    params.require(:prediction).permit(:image)
  end


end

web_app/app/helpers/application_helper.rb
module ApplicationHelper
end

web_app/app/helpers/predictions_helper.rb
module PredictionsHelper

  def emotions
    ['Angry', 'Disgust', 'Fear', 'Happy', 'Sad', 'Surprise', 'Neutral']
  end

  def predicted_value(values)
    emotions[values.index(values.max)]
  end

  def face_img(image_path)
    image_path[0...-4] + '_face' + image_path[-4..-1]
  end
end

web_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacialRecognitionApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:error] %>
      <div class="alert alert-danger" role="alert">
        <%= flash[:error] %>
      </div>
    <% end %>
    <%= link_to 'Upload Image', new_prediction_path, remote: true, 'data-toggle': 'modal', 'data-target': '#modal-prediction', class: 'btn btn-success'%>
    <div id="modal-prediction" class="modal" aria-labelledby="new-prediction-modal" role="dialog"></div>

    <%= yield %>
  </body>
</html>

web_app/app/views/predictions/_new.html.erb
<div class="modal-dialog"  id="new-prediction-modal">
  <div class="modal-content">
    <div class="modal-header">
      <h3>New Prediction</h3>
      <button type="button" class="btn btn-link text-uppercase font-weight-semibold" data-dismiss="modal">×</button>
    </div>
    <%= form_for @prediction, class: 'form-group', remote: true do |f| %>
        <div class="modal-body">

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">Upload</span>
                </div>
                <div class="custom-file">
                    <%= f.file_field :image, class: 'custom-file-input' %>
                    <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                </div>
            </div>
        </div>
        <div class='model-footer'>
            <button type="button" class="btn btn-link text-uppercase font-weight-semibold" data-dismiss="modal">Cancel</button>
            <%= f.submit 'Submit', class: 'btn btn-default' %>
        </div>
    <% end %>
  </div>
</div>

web_app/app/views/predictions/_prediction.html.erb
<div class='row border border-secondary mt-3 mx-auto'>
    <div class='row-md-4' >
        <%= image_tag prediction.image, class: 'img-fluid float-left', style: 'width: 200px;' %>
        <%= image_tag face_img(prediction.image.url), class: 'img-fluid float-left', style: 'width: 500px;'%>
    </div>
    <div class='row-md-1'>
        <h3>Status: <%= prediction.status.humanize %> <%= prediction.id%></h3>
        <%= button_to 'Delete', prediction_path(prediction), method: :delete, class: 'btn btn-danger ml-3'%>
    </div>


    <%#= render(partial: 'vote_button', locals: { prediction: prediction}) %>


    <%= render(partial: 'prediction_table', locals: { prediction: prediction}) unless prediction.predictions.nil? %>
</div>

web_app/app/views/predictions/_prediction_table.html.erb
<table class='table'>
        <thead>
            <tr>
                <th></th>
                <% emotions.each do |emotion|%>
                    <th scope='col'><%=emotion%></th>
                <%end%>
                <th scope=col>Results</th>
            </tr>
        </thead>
        <tbody>
            <% prediction.predictions.each do |key, values|%>
                <tr>
                    <th scope='row'><%=key.humanize%></th>
                    <% values.each do |value|%>
                        <td><%= '%.2f' % (value*100) %></td>
                    <% end %>
                    <td><%=predicted_value(values)%></td>
                </tr>
            <%end%>
        </tbody>
    </table>

web_app/app/views/predictions/_vote_button.html.erb
        <div class='row'>
            <h3 class='ml-3'>Upvotes: <%= prediction.upvote %></h3>
            <h3 class='ml-3'>Downvotes: <%= prediction.downvote %></h3>
        </div>

        <% if prediction.completed? %>
            <div class='row'>
                <%= button_to 'Upvote', upvote_prediction_path(prediction),method: :get, class: 'btn btn-success ml-3'%>
                <%= button_to 'Downvote', downvote_prediction_path(prediction),method: :get, class: 'btn btn-danger ml-3'%>
            </div>
        <% end %>

web_app/app/views/predictions/index.html.erb
<div class='row'>
<% @predictions.each do |prediction|%>
   <%= render prediction%>
<% end %>
</div>

web_app/app/views/predictions/new.js.erb
console.log('asd');
$("#modal-prediction").html("<%= escape_javascript(render 'predictions/new') %>");
$("#modal-prediction").modal('show');

web_app/app/views/predictions/show.html.erb
<script>
var timeout = window.setTimeout(() => {
  <% if @prediction.reload.in_progress? %>
    location.reload()
  <% end %>
}, 4000);
</script>
<%= link_to 'Index', predictions_path, class: 'btn btn-info'%>
<%= render @prediction%>